config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'user/personal/:id' => 'users#personal',as:"user_personal"

  resources :users, only: [:index, :show, :edit, :update]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :posts
  validates :group, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord

  belongs_to :post
  attachment :picture
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :title, length: { maximum: 15 }
  validates :caption, presence: true
  validates :caption,  length: { maximum: 300 }

  validate :presence_pictures

  belongs_to :user
  belongs_to :category
  has_many :pictures, dependent: :destroy

  accepts_attachments_for :pictures, attachment: :picture

  private
  def presence_pictures
    errors.add(:posts, "can't be blank") if pictures.size == 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { maximum: 10 }
  validates :name, length: { minimum: 2 }
  validates :name, presence: true
  validates :introduction, length: { maximum: 30 }
  attachment :profile_image

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_personal_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @post.pictures.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      @post.pictures.new
      render "new"
    end
  end

  def index
    @posts=Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @category = @post.category
    @pictures = @post.pictures
  end

  def edit
    @post = Post.find(params[:id])
    if current_user != @post.user
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:post).permit(:title, :caption, :user_id, :member, :category_id, pictures_pictures: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = user.posts
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_path
    end
  end

  def personal
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
about.html.erb

app/views/homes/top.html.erb
<div class="container">
  <div class="top-image">
    <div class="row titles">
      <h1 class="text-center font">WeLoveNogizaka46</h1>
      <h2 class="text-center a font">乃木坂４６の推しメンを共有しましょう</h2>
    </div>
    <div class="row top-ad">
      <div class="buttons">
        <span class="new-registration-button">
          <%= link_to new_user_registration_path, class: "btn-partial-line" do %>
            <i class="fa fa-caret-right"></i> 新規登録
          <% end %>
        </span>
        <span class="login-button">
          <%= link_to new_user_session_path, class: "btn-partial-line" do %>
            <i class="fa fa-caret-right"></i> ログイン
          <% end %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top header-color">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <span id="application-name">WeLoveNogizaka46</span>
      </div>
    </div>
    <nav id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- data-toggle="modal"　data-target="#sampleModal" モーダルを開くコード -->
        <!--ログイン時 -->
        <% if user_signed_in? %>
          <li class="menu">
            <%= link_to ' Personal',user_personal_path(current_user),class:"glyphicon glyphicon-home" %>
          </li>
          <li class="menu">
            <%= link_to ' User',users_path, class:"glyphicon glyphicon-user" %>
          </li>
          <li class="menu">
            <%= link_to ' Post',posts_path ,class:"glyphicon glyphicon-list-alt" %>
          </li>
          <li class="menu">
            <a href="" data-toggle="modal" data-target="#sampleModal">
              <i class="fas fa-search"></i>
            </a>
          </li>
          <li class="menu">
             <%= link_to ' Logout', destroy_user_session_path, method: :delete,class:"glyphicon glyphicon-log-out logout"%>
          </li>
            <!--ログアウト時 -->
        <% else %>
          <li class="menu">
            <%= link_to ' Home',root_path,class:"glyphicon glyphicon-home" %>
          </li>
          <li class="menu">
            <%= link_to ' About',home_about_path,class:"glyphicon glyphicon-link" %>
          </li>
          <!-- <li class="menu"> -->
            <%#= link_to ' User',users_path, class:"glyphicon glyphicon-user" %>
          <!-- </li> -->
          <!-- <li class="menu"> -->
            <%#= link_to ' Post',posts_path ,class:"glyphicon glyphicon-list-alt" %>
          <!-- </li> -->
          <li class="menu">
            <%= link_to ' Signup', new_user_registration_path,class:"glyphicon glyphicon-edit" %>
          </li>
          <li class="menu">
            <%= link_to ' Login', new_user_session_path ,class:"glyphicon glyphicon-log-in"%>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<!-- 検索ボタンをモーダル表示 -->
<div class="modal fade" id="sampleModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
        <h4 class="modal-title">検索</h4>
      </div>
      <!-- <div class="modal-body"> -->
        <!-- ログイン時のみ検索ボタンをヘッダーに表示 -->
        <%# if user_signed_in? %>
          <%#= form_tag(search_path, :method => 'get') do %>
            <%#= select_tag(:option, options_for_select([["ユーザー", "1"],["投稿","2"]]))%>
            <%#= text_field_tag :search %>
            <%#= submit_tag '検索' %>
          <%# end %>
        <%# end %>
        <!-- ここまで -->
      <!-- </div> -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>
<!-- モーダルここまで -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Number1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <div class="header-test">
        <%= render 'layouts/header'%>
      </div>
      <main class="main">
        <%= yield %>
      </main>
  </body>
  <footer>
    <div class="footer-logo">
      <div class="col-xs-3"></div>
      <div class="col-xs-6">
        <div id="footer-area">©WeloveNogizaka46</div>
      </div>
      <div class="col-xs-3"></div>
    </div>
  </footer>
</html>

  <!-- <body> -->
    <%#= yield %>
  <!-- </body> -->
<!-- </html> -->

app/views/posts/_form.html.erb
<%= form_with model:@post, html:{name: 'form'} do |f| %>
  <p class="form">
    <%= f.label :推しメン選択 %>
    <%= f.collection_select :post, Post.all, :id, :member,class:"select-controll" %>
  </p>
  <p class="form">
    <%= f.label :タイトル（15字以内）  %>
    <%= f.text_field :title,class:"btn-block form-controll" %>
  </p>
  <p class="form">
    <%= f.label :本文（300字以内） %>
    <%= f.text_area :caption,class:"btn-block form-controll" %>
    <!-- idを加えることでgetElementById("select_file")をとれる。 -->
  </p>
  <p class="form">
    <%= f.label :添付画像選択（1枚以上3枚以内） %>
    <%= f.attachment_field :pictures_pictures, multiple: true, id:"select_image" %>
  </p>
  <p class="form">
    <%= f.label :カテゴリー %>
    <%= f.collection_select :category_id, Category.all, :id, :group,class:"select-controll" %>
  </p>
  <div class="submit-button">
    <%= f.submit "投稿する",class: "btn btn-primary btn-block post-button",id:"submit_button" %>
  </div>
<% end %>

app/views/posts/_script.html.erb
<script>
  submit_button.addEventListener('click',(e) => {
    e.preventDefault();
    // preventDefault()=クリックイベントを無効化。無効化しないと無条件にデータを送信してします。
    var files = document.getElementById("select_image").files;
    // <div><h1>は全てElement。なので、select_fileという名前がついたid(Element)を呼び出す
    // files=html上の選択ボックスのtype
    if(files.length > 2) {
      alert('画像ファイルは2枚以内で投稿して下さい');
    }
    else {
       document.form.submit();
       // このformは5行目で任意につけたフォーム。このdocument.form.submit()で、preventDefault();で無効化したものを再度有効化している。
    }
  });
</script>

app/views/posts/edit.html.erb
<div class="row post-form">
  <div class="col-xs-1"></div>
  <div class=" col-xs-10">
    <h3 class="new_post">投稿編集</h3>
      <% if @post.errors.any? %>
        <%= render 'posts/alert', post: @post %>
      <% end %>
    <%= render 'posts/form', post: @post %>
  </div>
  <div class="col-xs-1"></div>
</div>
<%= render 'posts/script', post: @post %>

app/views/posts/new.html.erb
<div class="post-form">
  <div class="container">
    <div class="row">
      <div class="col-xs-1"></div>
      <div class=" col-xs-10">
        <h3 class="new_post">新規投稿</h3>
          <% if @post.errors.any? %>
            <%= render 'posts/alert', post: @post %>
          <% end %>
         <%= render 'posts/form', post: @post %>
     </div>
     <div class="col-xs-1"></div>
   </div>
 </div>
</div>
<%= render 'posts/script', post: @post %>

app/views/posts/show.html.erb
<div class="container">
  <h1 class="detail-title">ここがイチオシ！！</h1>
    <div class="row center-block">
      <span class="label label-primary">投稿者:<%= @user.name %></span>
      <span class="label label-primary">投稿日時:<%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span><br>
      <span class="label label-primary">推しメン:<%= @post.member %></span>
      <span class="label label-primary">カテゴリー:<%= @post.category.group %></span>
      <div class="post-show-buttons">
      <!-- ログイン時 -->
        <% if user_signed_in? %>
          <% if @user == current_user %>
            <span class="edit-button">
              <%= link_to "編集", edit_post_path(@post.id), class:"btn btn-success btn-sm" %>
            </span>
            <span class="destroy-button">
              <%= link_to "削除", post_path(@post.id),"data-confirm"=>"本当に削除しますか?", class:"btn btn-danger btn-sm", method: :delete %>
            </span>
          <% end %>
        <% end %>
        <!-- ここまで -->
      </div>
    </div>
    <div class="row center-block">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <%= @post.title %>
        </div>
        <div class="panel-body">
          <%= @post.caption %>
        </div>
      </div>
    </div>
    <div class="row text-center">
      <% @pictures.each do |picture| %>
        <%= attachment_image_tag picture, :image, format: 'jpeg', size:'310x310' %>
      <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="body-color">
  <div class="container">
    <div class="row">
      <div class="col-xs-1"></div>
      <div class=" col-xs-10">
        <h3 class="profile-edit">プロフィール編集</h3>
        <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <% if @user.errors.any? %>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        <% end %>
        <%= form_with(model: @user, local: true) do |f| %>
          <p class="form">
            <%= f.label :表記名 %>
            <%= f.text_field :name,class:"btn-block" %>
          </p>
          <p class="form">
            <%= f.label :自己紹介（30字以内）  %>
            <%= f.text_area :introduction,class:"btn-block" %>
          </p>
          <p class="form">
            <%= f.label :プロフィール画像 %>
            <%=f.attachment_field :profile_image %>
          </p>
          <p class="update_btn">
            <%= f.submit "更新",class:"btn btn-block btn-primary" %>
          </p>
        <% end %>
      </div>
      <div class="col-xs-1"></div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/personal.html.erb
<div class="container">
  <div class="row text-center">
    <% if @user == current_user %>
      <h1>マイページ</h1>
    <% else %>
      <h1><%= @user.name %>さんのプロフィール</h1>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <%= attachment_image_tag @user, :profile_image, size:"210x210", format: "jpeg", class: "img-circle", fallback: "default.jpg" %><br>
      <% if @user == current_user %>
        <%= link_to "プロフィール修正", edit_user_path(@user.id) %>
      <% end %>
    </div>
    <div class="col-xs-8">
      <div class="panel panel-info">
        <div class="panel-heading introduction-space">自己紹介</div>
        <div class="panel-body">
          <%= @user.introduction %>
        </div>
      </div>
    </div>
  </div>
  <div class="row text-center">
    <% if @user == current_user %>
      <%= link_to "推しメン投稿する",new_post_path %><br>
    <% end %>
    <%= link_to "投稿一覧",user_path(@user.id) %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row text-center">
    <h3><%= @user.name %>様の投稿一覧</h3>
  </div>
  <div class="row">
    <table class="table table-hover table-invrese">
      <thead>
        <tr>
          <th>推しメン</th>
          <th>タイトル</th>
          <th>カテゴリー</th>
          <th>投稿日時</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td>
              <span class="label label-primary">
                <%= post.member %>
              </span>
            </td>
            <td>
              <%= post.title %>
            </td>
            <td>
              <%= post.category.group %>
            </td>
            <td>
              <%= post.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
            </td>
            <td>
              <%= link_to "詳細画面" ,post_path(post.id) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="text-center">
      <%#= paginate @posts %>
    </div>
  </div>
</div>